-- AlterTable
ALTER TABLE "StudentTermFee" ADD COLUMN     "term1_fee" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "term2_fee" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN     "term3_fee" DECIMAL(65,30) NOT NULL DEFAULT 0;
